// <auto-generated />
namespace LojaVirtual.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InicializarBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicializarBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "201812031551464_InicializarBanco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
